url: 'http://localhost:5000/wps'
allowedinputpaths:
  - './static/'
default_mimetype: 'text/xml'
#default_mimetype: 'application/json'
#json_indent: -1
json_indent: 2

root: './static/data/maps'

dtm_color_palette: './static/data/color_files/color_file_1.txt'

dtm_geo: './static/data/maps/srtm_30k_global.tif'
#dtm_geo: '@xlink:href=file:./static/data/maps/srtm1_x35_y32.tif'

dtm_utm: './static/data/maps/srtm_30k_32636.tif'
dtm_utm_small: './static/data/maps/srtm1_boker_32636.tif'
